### ISSUE TITLE
Version 2.0.7.1 has dependancy on Newtonsoft.json.dll

### ISSUE THREAD

**Issue by Fulgan** [KoenZomers/KeePassOneDriveSync#106]
The latest version has dependancy to the Newtonsoft JSON parser but fails to include it. This causes Keepass to fail to compile the plgx:

[Window Title]
KeePass

[Content]
The following plugin is incompatible with the current KeePass version:
C:\Program Files (x86)\KeePass Password Safe 2\Plugins\KeeOneDriveSync.plgx

Have a look at the plugin's website for an appropriate version.

[Expanded Information]
Could not find a part of the path 'C:\Users\Steph.GIT\AppData\Local\Temp\7180F9546F180947B745500606CFD4E8\Packages\Newtonsoft.Json.8.0.1\lib\net45\Newtonsoft.Json.dll'.
mscorlib
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at KeePass.Plugins.PlgxCache.AddCacheFile(String strNormalFile, PlgxPluginInfo plgx)
   at KeePass.Plugins.PlgxPlugin.Compile(String strTmpRoot, PlgxPluginInfo plgx, String strBuildPre, String strBuildPost)
   at KeePass.Plugins.PlgxPlugin.ReadFile(BinaryReader br, PlgxPluginInfo plgx, IStatusLogger slStatus)
   at KeePass.Plugins.PlgxPlugin.LoadPriv(String strFilePath, IStatusLogger slStatus, Boolean bAllowCached, Boolean bAllowCompile, Boolean bAllowLoad, TextWriter twLog)
   at KeePass.Plugins.PlgxPlugin.Load(String strFilePath, IStatusLogger slStatus)
Void WinIOError(Int32, System.String)

[^] Details  [OK]

**Comment by KoenZomers** [comment]
Please download the re-released 2.0.7.1 which does have the file: https://github.com/KoenZomers/KeePassOneDriveSync/releases/tag/2.0.7.1-2
