### ISSUE TITLE
Crash if target directory exists

### ISSUE THREAD

**Issue by milnak** [KoenZomers/KeePassOneDriveSync#37]
Create a *directory* on OneDrive "/drive/root:/Documents/KeePass" then do a first sync.
Will get crash:
`
System.NullReferenceException: Object reference not set to an instance of an object.
   at KoenZomers.OneDrive.Api.OneDriveApi.<DownloadItemAndSaveAs>d__86.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at KoenZomersKeePassOneDriveSync.KeePassDatabase.<SyncDatabase>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at KoenZomersKeePassOneDriveSync.OneDriveConfigDetailsForm.<ForceSyncButton_Click>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
`

**Comment by KoenZomers** [comment]
Thanks for reporting this. I'll need more information on how to reproduce this. It works fine for me. How did you do the first sync? Did you open an existing KeePass database stored in that folder or did you open one locally and have it upload there?

**Comment by KoenZomers** [comment]
Closing due to no response
