### ISSUE TITLE
Microsoft Graph synchronization stopped working

### ISSUE THREAD

**Issue by drujd** [KoenZomers/KeePassOneDriveSync#54]
As of today, synchronization using Microsoft Graph stopped working. Syncing a OneDrive Business account results in a blank "Authenticate to OneDrive" windows without anything happening. Syncing a personal account shows "Authenticate to OneDrive" permissions yes/no window (which seems different from the last time, so maybe this is due to some changes to the API?). After clicking yes, unhandled exception is shown:
``See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
KoenZomers.OneDrive.Api.Exceptions.TokenRetrievalFailedException: Failed to retrieve OneDrive access token. Additional information: AADSTS90002: Tenant 9188040d-6c67-4c5b-b112-36a304b66dad not found. This may happen if there are no active subscriptions for the tenant. Check with your subscription administrator.
Trace ID: 03da7a2c-6136-44bc-ae00-50a488ac0900
Correlation ID: 7fb3bd84-199f-4213-ac5f-c915332703da
Timestamp: 2018-04-06 08:52:33Z
   at KoenZomers.OneDrive.Api.OneDriveApi.<PostToTokenEndPoint>d__51.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at KoenZomers.OneDrive.Api.OneDriveGraphApi.<GetAccessTokenFromAuthorizationToken>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at KoenZomers.OneDrive.Api.OneDriveGraphApi.<GetAccessTokenFromAuthorizationToken>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at KoenZomers.OneDrive.Api.OneDriveApi.<GetAccessToken>d__49.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at KoenZomersKeePassOneDriveSync.OneDriveAuthenticateForm.<WebBrowser_Navigated>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2633.0 built by: NET471REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
KeePass
    Assembly Version: 2.38.0.21288
    Win32 Version: 2.38.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/KeePass%20Password%20Safe%202/KeePass.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2633.0 built by: NET471REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
KeeAgent
    Assembly Version: 0.8.1.0
    Win32 Version: 0.8.1.0
    CodeBase: file:///C:/Users/jklos/AppData/Local/KeePass/PluginCache/5qsKoDoovis9IdKHBD6S/KeeAgent.dll
----------------------------------------
SshAgentLib
    Assembly Version: 0.8.1.0
    Win32 Version: 0.8.1.0
    CodeBase: file:///C:/Users/jklos/AppData/Local/KeePass/PluginCache/5qsKoDoovis9IdKHBD6S/SshAgentLib.DLL
----------------------------------------
SshAgentLib.WinForms
    Assembly Version: 0.8.1.0
    Win32 Version: 0.8.1.0
    CodeBase: file:///C:/Users/jklos/AppData/Local/KeePass/PluginCache/5qsKoDoovis9IdKHBD6S/SshAgentLib.WinForms.DLL
----------------------------------------
KoenZomersKeePassOneDriveSync
    Assembly Version: 2.0.1.2
    Win32 Version: 2.0.1.2
    CodeBase: file:///C:/Users/jklos/AppData/Local/KeePass/PluginCache/2CL4vPGfal3V5F93ELZm/KoenZomersKeePassOneDriveSync.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 8.0.0.0
    Win32 Version: 8.0.3.19514
    CodeBase: file:///C:/Users/jklos/AppData/Local/KeePass/PluginCache/2CL4vPGfal3V5F93ELZm/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2633.0 built by: NET471REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
KeePassHttp
    Assembly Version: 2.34.0.0
    Win32 Version: 1.8.4.2
    CodeBase: file:///C:/Users/jklos/AppData/Local/KeePass/PluginCache/lhdEitf1M658B1uFQktH/KeePassHttp.dll
----------------------------------------
KeePass.XmlSerializers
    Assembly Version: 2.38.0.21288
    Win32 Version: 2.38.0.21288
    CodeBase: file:///C:/Program%20Files%20(x86)/KeePass%20Password%20Safe%202/KeePass.XmlSerializers.DLL
----------------------------------------
System.Security
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Security/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Security.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
BouncyCastle.Crypto
    Assembly Version: 1.7.4137.9688
    Win32 Version: 1.7.4137.9688
    CodeBase: file:///C:/Users/jklos/AppData/Local/KeePass/PluginCache/5qsKoDoovis9IdKHBD6S/BouncyCastle.Crypto.DLL
----------------------------------------
KoenZomers.OneDrive.Api
    Assembly Version: 2.1.0.1
    Win32 Version: 2.1.0.1
    CodeBase: file:///C:/Users/jklos/AppData/Local/KeePass/PluginCache/2CL4vPGfal3V5F93ELZm/KoenZomers.OneDrive.Api.DLL
----------------------------------------
Microsoft.mshtml
    Assembly Version: 7.0.3300.0
    Win32 Version: 7.0.3300.0
    CodeBase: file:///C:/WINDOWS/assembly/GAC/Microsoft.mshtml/7.0.3300.0__b03f5f7f11d50a3a/Microsoft.mshtml.dll
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2633.0 built by: NET471REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.``

Deleting the sync configurations and creating them again does not help this time around.

**Comment by KoenZomers** [comment]
Thanks for reporting this. I can reproduce it and will look into this.

**Comment by KoenZomers** [comment]
It should work again now. There was a mayor outage of Azure Active Directory at Microsoft which caused the issue. Can you check if it works again now for you?
