### ISSUE TITLE
KeePassOneDriveSync stopped working ~30 mins ago

### ISSUE THREAD

**Issue by drujd** [KoenZomers/KeePassOneDriveSync#72]
When syncing to work Office365 OneDrive account:
```
System.ComponentModel.Win32Exception (0x80004005): The client and server cannot communicate, because they do not possess a common algorithm
   at System.Net.SSPIWrapper.AcquireCredentialsHandle(SSPIInterface SecModule, String package, CredentialUse intent, SecureCredential scc)
   at System.Net.Security.SecureChannel.AcquireCredentialsHandle(CredentialUse credUsage, SecureCredential& secureCredential)
   at System.Net.Security.SecureChannel.AcquireClientCredentials(Byte[]& thumbPrint)
   at System.Net.Security.SecureChannel.GenerateToken(Byte[] input, Int32 offset, Int32 count, Byte[]& output)
   at System.Net.Security.SecureChannel.NextMessage(Byte[] incoming, Int32 offset, Int32 count)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.TlsStream.ProcessAuthentication(LazyAsyncResult result)
   at System.Net.TlsStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback asyncCallback, Object asyncState)
   at System.Net.ConnectStream.WriteHeaders(Boolean async)
```

When syncing to personal free OneDrive account:
![image](https://user-images.githubusercontent.com/6545887/49376365-4472b500-f707-11e8-8404-2e72334473a4.png)

**Comment by drujd** [comment]
I guess MS made some changes to HTTPS/TLS/accepted crypto for Graph API?

**Comment by drujd** [comment]
When setting non-graph api sync, I receive the same exception even when syncing to personal account.

**Comment by KoenZomers** [comment]
I just tried setting up a new connection to a OneDrive for Business through an Office 365 account through the Graph API provider here and it works fine. It sounds a bit like something is intercepting your network traffic. Are you on a network with a (transparent) proxy by chance? Can you try this on a different connection?

**Comment by drujd** [comment]
While I am behind a firewall, everything worked earlier today and I am not aware of any changes in network configuration.

Also, I have tried using my phone's tethered connection over LTE (so no firewall) and had the exact same issues. Never had any such (HTTPS/TLS) problem before.

**Comment by drujd** [comment]
Works fine from my home computer. Weird.

**Comment by drujd** [comment]
Found the culprit! I had TLS 1.0 disabled through registry values in "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0". How those settings got there, I don't know - "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols" is empty on a clean Windows install and it is not part of group policies enforced on my PC, maybe some one time script from our IT?

Anyway, removing it fixed the issue.

However: If I understand correctly, that means that the plugin is using TLS 1.0 at best?! The only secure version of TLS is 1.2 (and 1.3, which is really not supported almost anywhere)...

**Comment by KoenZomers** [comment]
Just ran some tests for this one. Wireshark is only showing TLS 1.2 to be used. I've explicitly disabled TLS 1.0 in the registry like you reported: did not make any difference here. I believe Microsoft made a change recently to phase out TLS 1.0. The KeePass plugins still use .NET 4.5.2 as this is what KeePass dictates. .NET 4.5 defaults to TLS 1.0 by default unless not otherwise possible. I have updated the plugin code to default to TLS 1.2 instead. So this problem should not occur anymore.

Released in https://github.com/KoenZomers/KeePassOneDriveSync/releases/tag/2.0.2.5

Closing issue. Feel free to reopen in case it still occurs.

**Comment by drujd** [comment]
It works now, thanks!
